[server]
headless = true
port = 3000
enableCORS = false

[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#d4d4d4"

font = "sans serif"

[logger]
level = "debug"
